In [2]:
import matplotlib.pyplot as plt
import numpy as np 
import pandas as pd
import random
import re

In [3]:
df_archivo = pd.read_csv('definitivo.csv', index_col= 0)
df_archivo.head(2)

,case_number,year,type,country,area,location,activity,name,sex_,age,time,species_,href,fatal_(y/n),injury,date
0,1800.00.00,1800.0,Unprovoked,SEYCHELLES,St. Anne,NaN,a corsair's boat was overturned,NaN,F,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,Y,"FATAL, all onboard were killed by sharks",1800
1,1797.05.28.R,1797.0,Unprovoked,NaN,NaN,NaN,Dropped overboard,child,NaN,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,Y,FATAL,Reported May-28-1797

In [4]:
# Cread una columna nueva y una función que nos dé el mes donde ocurrió el ataque. Si no hay info del mes, que devuelva un nulo (NaN)
#def mes():
fecha = df_archivo['date']
fecha

0                       1800
1       Reported May-28-1797
2                12-Sep-1792
3                       1791
4                10-May-1788
                ...
6279    Reported 26-Feb-1804
6280             May-17-1803
6281                Mar-1803
6282    Reported Apr-13-1802
6283    Reported 18-Dec-1801
Name: date, Length: 6284, dtype: object

In [5]:
# patron = r'-\b\{w3}\b-'
string = "18-Oct-2000", "Oct-18-2000",

In [5]:
re.findall(patron, string)[0]               #lo convertimos a una lista con un elemento [0]

'Oct'

In [21]:
def sacar_mes(col):
    patron = r"(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)" 
    x = re.findall(patron, col)
    try:
        return x[0]
    except:
        return "unspecified"

In [22]:
df_archivo['fecha_limpia'] = df_archivo['date'].apply(sacar_mes)

In [23]:
df_archivo['fecha_limpia']. value_counts()

Jul            669
Aug            599
Sep            553
Jan            518
unspecified    517
Jun            495
Apr            454
Oct            443
Dec            436
Mar            413
Nov            408
May            397
Feb            382
Name: fecha_limpia, dtype: int64

In [24]:
pd.options.display.max_rows = None
df_archivo['fecha_limpia']

0       unspecified
1               May
2               Sep
3       unspecified
4               May
5               Jul
6               Aug
7               Sep
8               Dec
9               Mar
10              Aug
11      unspecified
12      unspecified
13      unspecified
14              Jul
15      unspecified
16      unspecified
17      unspecified
18              Oct
19              Jul
20      unspecified
21      unspecified
22      unspecified
23              Dec
24              Apr
25      unspecified
26      unspecified
27              Jun
28              Mar
29      unspecified
30      unspecified
31      unspecified
32      unspecified
33      unspecified
34      unspecified
35      unspecified
36      unspecified
37      unspecified
38              Jan
39      unspecified
40      unspecified
41      unspecified
42      unspecified
43      unspecified
44      unspecified
45      unspecified
46      unspecified
47      unspecified
48      unspecified
49      unspecified
50      unspecified
51      unspecified
52              Oct
53      unspecified
54      unspecified
55      unspecified
56      unspecified
57      unspecified
58      unspecified
59      unspecified
60      unspecified
61      unspecified
62      unspecified
63      unspecified
64      unspecified
65      unspecified
66      unspecified
67      unspecified
68      unspecified
69      unspecified
70      unspecified
71      unspecified
72      unspecified
73              Jun
74      unspecified
75      unspecified
76      unspecified
77      unspecified
78      unspecified
79      unspecified
80      unspecified
81      unspecified
82      unspecified
83      unspecified
84      unspecified
85      unspecified
86      unspecified
87              Feb
88              May
89              Mar
90      unspecified
91              Aug
92              Aug
93      unspecified
94      unspecified
95      unspecified
96      unspecified
97              Jan
98      unspecified
99              May
100     unspecified
101     unspecified
102     unspecified
103     unspecified
104             Aug
105     unspecified
106     unspecified
107     unspecified
108     unspecified
109     unspecified
110     unspecified
111     unspecified
112     unspecified
113             Jun
114             Apr
115     unspecified
116     unspecified
117     unspecified
118     unspecified
119     unspecified
120     unspecified
121     unspecified
122     unspecified
123     unspecified
124     unspecified
125             Mar
126     unspecified
127     unspecified
128     unspecified
129     unspecified
130     unspecified
131     unspecified
132     unspecified
133     unspecified
134     unspecified
135     unspecified
136     unspecified
137     unspecified
138     unspecified
139     unspecified
140     unspecified
141     unspecified
142     unspecified
143     unspecified
144     unspecified
145     unspecified
146     unspecified
147     unspecified
148     unspecified
149     unspecified
150     unspecified
151     unspecified
152     unspecified
153     unspecified
154     unspecified
155     unspecified
156             Jul
157             Jul
158             Jul
159     unspecified
160     unspecified
161     unspecified
162     unspecified
163     unspecified
164     unspecified
165     unspecified
166     unspecified
167     unspecified
168     unspecified
169     unspecified
170             Jun
171             Jun
172             Jun
173             Jun
174             Jun
175             Jun
176             Jun
177             May
178             May
179             May
180             May
181             May
182             May
183             May
184             May
185             May
186             May
187             Apr
188             Apr
189             Apr
190             Apr
191             Apr
192             Apr
193             Apr
194             Apr
195             Apr
196             Apr
197             Apr
198             Apr
199             Apr
200             Apr
201             Apr
202             Apr
203             Apr
204             Apr
205             Mar
206             Mar
207             Mar
208             Mar
209             Feb
210             Feb
211             Feb
212             Feb
213             Feb
214             Feb
215             Feb
216             Feb
217             Jan
218             Jan
219             Jan
220             Jan
221             Jan
222             Jan
223             Dec
224             Dec
225             Dec
226             Dec
227             Nov
228             Nov
229             Nov
230             Nov
231             Nov
232             Nov
233             Nov
234             Nov
235             Oct
236             Oct
237             Oct
238             Oct
239             Oct
240             Oct
241             Oct
242             Oct
243             Oct
244             Oct
245             Oct
246             Oct
247             Sep
248             Sep
249             Sep
250             Sep
251             Sep
252             Sep
253             Sep
254             Sep
255             Sep
256             Sep
257             Sep
258             Sep
259             Sep
260             Sep
261             Sep
262             Sep
263             Sep
264             Sep
265             Sep
266             Aug
267             Aug
268             Aug
269             Aug
270             Aug
271             Aug
272             Aug
273             Aug
274             Aug
275             Aug
276             Jul
277             Jul
278             Jul
279             Jul
280             Jul
281             Jul
282             Jul
283             Jul
284             Jul
285             Jul
286             Jul
287             Jul
288             Jul
289             Jul
290             Jul
291             Jul
292             Jul
293             Jul
294             Jul
295             Jun
296             Jun
297             Jun
298             Jun
299             Jun
300             Jun
301     unspecified
302             Jun
303             Jun
304             Jun
305             Jun
306             Jun
307             Jun
308             Jun
309             May
310             May
311             May
312             May
313             May
314             May
315             May
316             Apr
317             Apr
318             Apr
319             Apr
320             Apr
321             Apr
322             Apr
323             Apr
324             Apr
325             Apr
326             Apr
327             Apr
328             Apr
329             Apr
330             Apr
331             Apr
332             Apr
333             Apr
334             Apr
335             Apr
336             Apr
337             Mar
338             Mar
339             Mar
340             Mar
341             Mar
342             Feb
343             Feb
344             Feb
345             Feb
346             Feb
347             Feb
348             Feb
349             Feb
350             Feb
351             Jan
352             Jan
353             Jan
354             Jan
355             Jan
356             Jan
357             Jan
358             Jan
359             Dec
360             Dec
361             Dec
362             Dec
363             Dec
364             Dec
365             Dec
366             Dec
367             Nov
368             Nov
369             Oct
370             Oct
371             Oct
372             Oct
373             Oct
374             Oct
375             Oct
376             Oct
377             Oct
378             Oct
379             Oct
380             Sep
381             Sep
382             Sep
383             Sep
384             Sep
385             Sep
386             Sep
387             Sep
388             Sep
389             Sep
390             Sep
391             Sep
392             Sep
393             Sep
394             Sep
395             Sep
396             Aug
397             Aug
398             Aug
399             Aug
400             Aug
401             Aug
402             Aug
403             Jul
404             Jul
405             Jul
406             Jul
407             Jul
408             Jul
409             Jul
410             Jul
411             Jul
412             Jul
413             Jul
414             Jul
415             Jul
416             Jul
417             Jul
418             Jul
419             Jul
420             Jul
421             Jul
422             Jul
423             Jul
424             Jun
425             Jun
426             Jun
427             Jun
428             Jun
429             Jun
430             Jun
431             Jun
432             Jun
433             Jun
434             Jun
435             Jun
436             Jun
437             Jun
438             Jun
439             Jun
440             May
441             May
442             May
443             May
444             May
445             May
446             May
447             May
448             May
449             May
450             Apr
451             Apr
452             Apr
453             Apr
454             Apr
455             Apr
456             Apr
457             Apr
458             Apr
459             Apr
460             Apr
461             Mar
462             Mar
463             Mar
464             Mar
465             Mar
466             Mar
467             Mar
468             Mar
469             Mar
470             Mar
471             Mar
472             Feb
473             Feb
474             Feb
475             Feb
476             Feb
477             Feb
478             Feb
479             Feb
480             Jan
481             Jan
482             Jan
483             Jan
484             Jan
485             Jan
486             Jan
487             Jan
488             Jan
489             Dec
490             Dec
491             Dec
492             Dec
493             Dec
494             Dec
495             Dec
496             Dec
497             Dec
498             Nov
499             Nov
500             Nov
501             Nov
502             Nov
503             Nov
504             Nov
505             Nov
506             Nov
507             Oct
508             Oct
509             Oct
510             Oct
511             Oct
512             Oct
513             Oct
514             Oct
515             Oct
516             Oct
517             Oct
518             Oct
519             Oct
520             Oct
521             Oct
522             Oct
523             Sep
524             Sep
525             Sep
526             Sep
527             Sep
528             Sep
529             Sep
530             Sep
531             Sep
532             Sep
533             Sep
534             Sep
535             Sep
536             Sep
537             Sep
538             Sep
539             Sep
540             Aug
541             Aug
542             Aug
543             Aug
544             Aug
545             Aug
546             Aug
547             Aug
548             Aug
549             Jul
550             Jul
551             Jul
552             Jul
553             Jul
554             Jul
555             Jul
556             Jul
557             Jul
558             Jul
559             Jul
560             Jul
561             Jul
562             Jul
563             Jul
564             Jul
565             Jul
566             Jul
567             Jun
568             Jun
569             Jun
570             Jun
571             Jun
572             Jun
573             Jun
574             Jun
575             Jun
576             Jun
577             Jun
578             Jun
579             Jun
580             Jun
581             Jun
582             Jun
583             Jun
584             Jun
585             Jun
586             Jun
587             Jun
588             May
589             May
590             May
591             May
592             May
593             May
594             May
595             May
596             May
597             May
598             Apr
599             Apr
600             Apr
601             Jun
602             Apr
603             Apr
604             Apr
605             Apr
606             Mar
607             Mar
608             Mar
609             Mar
610             Mar
611             Mar
612             Mar
613             Mar
614             Mar
615             Feb
616             Feb
617             Feb
618             Feb
619             Feb
620             Jan
621             Jan
622             Jan
623             Jan
624             Jan
625             Jan
626             Jan
627             Jan
628             Jan
629             Jan
630             Jan
631             Jan
632             Dec
633             Dec
634             Dec
635             Dec
636             Dec
637             Dec
638             Dec
639             Dec
640             Dec
641             Nov
642             Nov
643             Nov
644             Nov
645             Nov
646             Nov
647             Nov
648             Nov
649             Oct
650             Oct
651             Oct
652             Oct
653             Oct
654             Oct
655             Oct
656             Oct
657             Oct
658             Oct
659             Oct
660             Oct
661             Oct
662             Oct
663             Oct
664             Oct
665             Oct
666             Sep
667             Sep
668             Sep
669             Sep
670             Sep
671             Sep
672             Sep
673             Sep
674             Aug
675             Aug
676             Aug
677             Aug
678             Aug
679             Aug
680             Aug
681             Aug
682             Aug
683             Aug
684             Aug
685             Aug
686             Aug
687             Aug
688             Aug
689             Aug
690             Aug
691             Aug
692             Aug
693             Aug
694             Jul
695             Jul
696             Jul
697             Jul
698             Jul
699             Jul
700             Jul
701             Jul
702             Jul
703             Jul
704             Jul
705             Jul
706             Jun
707             Jun
708             Jun
709             Jun
710             Jun
711             Jun
712             Jun
713             Jun
714             Jun
715             Jun
716             Jun
717             Jun
718             Jun
719             May
720             May
721             May
722             May
723             May
724             May
725             May
726             May
727             May
728             May
729             May
730             Apr
731             Apr
732             Apr
733             Apr
734             Apr
735             Apr
736             Apr
737             Apr
738             Mar
739             Mar
740             Mar
741             Mar
742             Mar
743             Mar
744             Mar
745             Mar
746             Mar
747             Mar
748             Feb
749             Feb
750             Feb
751             Feb
752             Feb
753             Jan
754             Jan
755             Jan
756     unspecified
757     unspecified
758             Dec
759             Dec
760             Dec
761             Dec
762             Dec
763             Dec
764             Dec
765             Nov
766             Nov
767             Nov
768             Nov
769             Nov
770             Nov
771             Nov
772             Nov
773             Oct
774             Oct
775             Oct
776             Oct
777             Oct
778             Oct
779             Oct
780             Oct
781             Oct
782             Oct
783             Oct
784             Sep
785             Sep
786             Sep
787             Sep
788             Sep
789             Sep
790             Sep
791             Sep
792             Sep
793             Sep
794             Sep
795             Sep
796             Sep
797             Sep
798             Aug
799             Aug
800             Aug
801             Aug
802             Aug
803             Aug
804             Aug
805             Aug
806             Aug
807             Aug
808             Aug
809             Aug
810             Aug
811             Jul
812             Jul
813             Jul
814             Jul
815             Jul
816             Jul
817             Jul
818             Jul
819             Jul
820             Jul
821             Jul
822             Jul
823             Jul
824             Jul
825             Jul
826             Jun
827             Jun
828             Jun
829             Jun
830             Jun
831             Jun
832             Jun
833             Jun
834             Jun
835             Jun
836             Jun
837             Jun
838             May
839             May
840             May
841             May
842             May
843             May
844             May
845             May
846             Apr
847             Apr
848             Apr
849             Apr
850             Apr
851             Apr
852             Apr
853             Apr
854             Apr
855             Apr
856             Apr
857             Mar
858             Mar
859             Mar
860             Mar
861             Mar
862             Mar
863             Mar
864             Mar
865             Mar
866             Mar
867             Feb
868             Feb
869             Feb
870             Feb
871             Feb
872             Feb
873             Jan
874             Jan
875             Jan
876             Jan
877             Jan
878             Jan
879             Dec
880             Dec
881             Dec
882             Dec
883             Dec
884             Dec
885             Dec
886             Dec
887             Nov
888             Nov
889             Nov
890             Nov
891             Nov
892             Nov
893             Oct
894             Oct
895             Oct
896             Oct
897             Oct
898             Oct
899             Oct
900             Oct
901             Oct
902             Oct
903             Sep
904             Sep
905             Sep
906             Sep
907             Sep
908             Sep
909             Sep
910             Sep
911             Sep
912             Sep
913             Sep
914             Sep
915             Aug
916             Aug
917             Aug
918             Aug
919             Aug
920             Aug
921             Aug
922             Aug
923             Jul
924             Jul
925             Jul
926             Jul
927             Jul
928             Jul
929             Jul
930             Jul
931             Jul
932             Jul
933             Jul
934             Jul
935             Jul
936             Jul
937             Jun
938             Jun
939             Jun
940             Jun
941             Jun
942             Jun
943             Jun
944             Jun
945             Jun
946             Jun
947             Jun
948             Jun
949             Jun
950             Jun
951             Jun
952             Jun
953             Jun
954             Jun
955             Jun
956             May
957             May
958             May
959             May
960             May
961             May
962             May
963             May
964             Apr
965             Apr
966             Apr
967             Apr
968             Apr
969             Mar
970             Mar
971             Mar
972             Mar
973             Mar
974             Mar
975             Mar
976             Mar
977             Mar
978             Mar
979             Mar
980             Mar
981             Mar
982             Feb
983             Feb
984             Feb
985             Feb
986             Jan
987             Jan
988             Jan
989             Jan
990             Jan
991             Jan
992             Jan
993             Jan
994             Jan
995             Dec
996             Dec
997             Dec
998             Dec
999             Dec

In [9]:
df_archivo['fecha_limpia'].unique()

array([nan, 'May', 'Sep', 'Jul', 'Aug', 'Dec', 'Mar', 'Oct', 'Apr', 'Jan',
       'Jun', 'Feb', 'and', 'the', 'War', 'few', 'Nov', 'Mid', 'day',
       'mid', 'Day'], dtype=object)

In [25]:
# Vamos con la columna fatal_(y/n). Lo primero que tenéis que hacer es evaluar los valores únicos que hay. 
# Esperaríamos tener solo dos valores: y y n, pero tristemente no es así. 
# Cread una columna nueva y una función que devuelva unicamente y o n y que devuelva un nulo (NaN) si no se encuentra el valor.

fatal = df_archivo['fatal_(y/n)']
fatal.unique()

array(['Y', 'N', nan, 'UNKNOWN', 'M', '2017', ' N', 'N ', 'y'],
      dtype=object)

In [11]:
def limpieza(column):
    if column == 'Y' or column == 'y':
        return 'Y'
    elif column == 'N' or column == ' N' or column == 'N ':
        return 'N'
    else:
        return np.NaN

In [81]:
#otra forma de hacerlo... 
def limpieza2(col):
    try:            
        col = col.strip().lower()                       # limpiamos brevemente antes de hacer el if con strip, lower.
        if col == "N" or col == "M":                    # si no ponemos el try y el except nos daría un error sobre floats, ¿pq?
                                                        # pq para Py los nans los entiende como floats. Lo evitamos con try/except
            return "N"
        elif col == "Y":
            return "Y"
        else:
            np.nan
    except:
        return np.nan

In [12]:
df_archivo['fatal_clean'] = df_archivo['fatal_(y/n)'].apply(limpieza)
df_archivo.sample()

,case_number,year,type,country,area,location,activity,name,sex_,age,time,species_,href,fatal_(y/n),injury,date,fecha_limpia,fatal_clean
4586,1951.11.28.b,1951.0,Unprovoked,JAMAICA,Kingston Parish,Kingston Harbor,Fishing,George Lewis,M,81,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,N,Lacerations to left hand,28-Nov-1951,Nov,N

In [13]:
df_archivo['fatal_clean'] = df_archivo['fatal_(y/n)'].apply(limpieza2)
df_archivo.sample()

NameError: name 'limpieza2' is not defined

In [14]:
#comprobamos que la columna está limpia
df_archivo['fatal_clean'].unique()

array(['Y', 'N', nan], dtype=object)

In [26]:
# Seguid la misma lógica que en el ejercicio anterior pero con la columna sex. 
# Pero en este caso vamos a incluir un retito más: En este caso querremos tener dos valores únicos F y M. 
# De nuevo en la columna hay otros carácteres raros como 'M ', 'lli', 'N', '.'. 
# En esos casos, queremos que se reemplacen por M o F de forma aleatoria (tendréis que usar la librería random). 
# En caso de que sea nulo, que la función devuelva nulo (np.nan).

sexo = df_archivo['sex_']
sexo.unique()

array(['F', nan, 'M', 'M ', 'lli', 'N', '.'], dtype=object)

In [15]:
def limpieza_2(column):
    lista = ['F', 'M']
    if column == 'F':
        return 'F'
    elif column == 'M' or column == 'M ' or column == 'N':
        return 'M'
    elif column == 'lli' or column == '.':
        return random.choice(lista)
    else:
        return np.NaN

In [16]:
df_archivo['sexo'] = df_archivo['sex_'].apply(limpieza_2)
df_archivo['sexo'].unique()

array(['F', nan, 'M'], dtype=object)

In [29]:
del df_archivo['href']

In [30]:
df_archivo.head()

,case_number,year,type,country,area,location,activity,name,sex_,age,time,species_,fatal_(y/n),injury,date,fecha_limpia,fatal_clean,sexo
0,1800.00.00,1800.0,Unprovoked,SEYCHELLES,St. Anne,NaN,a corsair's boat was overturned,NaN,F,NaN,NaN,NaN,Y,"FATAL, all onboard were killed by sharks",1800,unspecified,Y,F
1,1797.05.28.R,1797.0,Unprovoked,NaN,NaN,NaN,Dropped overboard,child,NaN,NaN,NaN,NaN,Y,FATAL,Reported May-28-1797,May,Y,NaN
2,1792.09.12,1792.0,Provoked,ENGLAND,NaN,On the Thames River,Fishing,male,M,NaN,NaN,NaN,Y,"FATAL, PROVOKED INCIDENT",12-Sep-1792,Sep,Y,M
3,1791.00.00,1791.0,Unprovoked,AUSTRALIA,New South Wales,Port Jackson,NaN,"female, an Australian aboriginal",F,NaN,NaN,NaN,Y,"FATAL, ""bitten in two""",1791,unspecified,Y,F
4,1788.05.10,1788.0,Boat,AUSTRALIA,New South Wales,Sydney Harbor,Fishing,boat,NaN,NaN,NaN,NaN,N,"No injury to occupants, shark bit oar and rudder",10-May-1788,May,N,NaN

In [46]:
df_archivo.to_csv("definitivo_limpieza2.csv")

In [27]:
df_archivo["fecha_limpia"].unique()

array(['unspecified', 'May', 'Sep', 'Jul', 'Aug', 'Dec', 'Mar', 'Oct',
       'Apr', 'Jun', 'Jan', 'Feb', 'Nov'], dtype=object)

In [32]:
df_archivo2 = df_archivo.copy()
df_archivo2.head(2)

,case_number,year,type,country,area,location,activity,name,sex_,age,time,species_,fatal_(y/n),injury,date,fecha_limpia,fatal_clean,sexo
0,1800.00.00,1800.0,Unprovoked,SEYCHELLES,St. Anne,NaN,a corsair's boat was overturned,NaN,F,NaN,NaN,NaN,Y,"FATAL, all onboard were killed by sharks",1800,unspecified,Y,F
1,1797.05.28.R,1797.0,Unprovoked,NaN,NaN,NaN,Dropped overboard,child,NaN,NaN,NaN,NaN,Y,FATAL,Reported May-28-1797,May,Y,NaN

In [34]:
del df_archivo2["fatal_(y/n)"]

In [33]:
del df_archivo2["date"]

In [38]:
del df_archivo2["sex_"]

In [ ]:
'case_number', 'year', 'type', 'country', 'area', 'location', 'activity', 'name', 'age', 'time', 'species', 'injury', 'fecha_limpia', 'fatal_limpio', 'sexo'

In [43]:
df_archivo2 = df_archivo2.rename(columns = {'species_':'species', "fatal_clean": 'fatal_limpio'})

In [44]:
df_archivo2.columns

Index(['case_number', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'age', 'time', 'species', 'injury', 'fecha_limpia',
       'fatal_limpio', 'sexo'],
      dtype='object')

In [45]:
df_archivo2.head(2)

,case_number,year,type,country,area,location,activity,name,age,time,species,injury,fecha_limpia,fatal_limpio,sexo
0,1800.00.00,1800.0,Unprovoked,SEYCHELLES,St. Anne,NaN,a corsair's boat was overturned,NaN,NaN,NaN,NaN,"FATAL, all onboard were killed by sharks",unspecified,Y,F
1,1797.05.28.R,1797.0,Unprovoked,NaN,NaN,NaN,Dropped overboard,child,NaN,NaN,NaN,FATAL,May,Y,NaN

In [48]:
df_archivo2.to_csv("definitivo_limpieza.csv")
df_archivo2.head(2)

,case_number,year,type,country,area,location,activity,name,age,time,species,injury,fecha_limpia,fatal_limpio,sexo
0,1800.00.00,1800.0,Unprovoked,SEYCHELLES,St. Anne,NaN,a corsair's boat was overturned,NaN,NaN,NaN,NaN,"FATAL, all onboard were killed by sharks",unspecified,Y,F
1,1797.05.28.R,1797.0,Unprovoked,NaN,NaN,NaN,Dropped overboard,child,NaN,NaN,NaN,FATAL,May,Y,NaN